# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EpfCli < Formula
  desc "CLI tool for the Emergent Product Framework (EPF) — validation, health checks, and MCP tooling for AI-assisted strategy"
  homepage "https://github.com/emergent-company/emergent.strategy"
  version "0.25.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emergent-company/emergent.strategy/releases/download/v0.25.0/epf-cli_0.25.0_darwin_amd64.tar.gz"
      sha256 "b745d409a8f5a0c7234be28831b80926fd49621c8c48ef8233890af60bc66d11"

      define_method(:install) do
        bin.install "epf-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emergent-company/emergent.strategy/releases/download/v0.25.0/epf-cli_0.25.0_darwin_arm64.tar.gz"
      sha256 "9d156e67dc1bda1d30829726a6281226854ddfb1c47dce961f483dd16e7e3c6e"

      define_method(:install) do
        bin.install "epf-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/emergent-company/emergent.strategy/releases/download/v0.25.0/epf-cli_0.25.0_linux_amd64.tar.gz"
      sha256 "672d56d9867a42b71509affe9616caccc15daf25c6097c30d9247b815794011b"
      define_method(:install) do
        bin.install "epf-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/emergent-company/emergent.strategy/releases/download/v0.25.0/epf-cli_0.25.0_linux_arm64.tar.gz"
      sha256 "044bbdbca8d20ddc22749139940bd11eba93a07fc231dc19b61909778f637838"
      define_method(:install) do
        bin.install "epf-cli"
      end
    end
  end

  test do
    system bin/"epf-cli", "version"
  end
end
