# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EpfCli < Formula
  desc "CLI tool for the Emergent Product Framework (EPF) — validation, health checks, and MCP tooling for AI-assisted strategy"
  homepage "https://github.com/emergent-company/emergent.strategy"
  version "0.29.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emergent-company/emergent.strategy/releases/download/v0.29.3/epf-cli_0.29.3_darwin_amd64.tar.gz"
      sha256 "a1241e1c88e49a9cc8ec9c8758588dae31bb7674d52f35292e9dc426f4cd1b28"

      define_method(:install) do
        bin.install "epf-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emergent-company/emergent.strategy/releases/download/v0.29.3/epf-cli_0.29.3_darwin_arm64.tar.gz"
      sha256 "2a8d77aa06348caccb44927280c74496e7673235fc54c334e680468c85ee51c3"

      define_method(:install) do
        bin.install "epf-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/emergent-company/emergent.strategy/releases/download/v0.29.3/epf-cli_0.29.3_linux_amd64.tar.gz"
      sha256 "3ac6e14651efccd0f263147081bbb570058b03f440467ab8eadad94a1e47c985"
      define_method(:install) do
        bin.install "epf-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/emergent-company/emergent.strategy/releases/download/v0.29.3/epf-cli_0.29.3_linux_arm64.tar.gz"
      sha256 "1aa5f166a4356d5a73c862275c35f8f88c1b44d4f8b9b5e220e8255399829f88"
      define_method(:install) do
        bin.install "epf-cli"
      end
    end
  end

  test do
    system bin/"epf-cli", "version"
  end
end
